### ISSUE TITLE
Java functions (java-functions branch) won't deploy on Windows due to CRLF line endings

### ISSUE THREAD

**Issue by SCWells72** [trailheadapps/functions-recipes#139]
### Summary

Filing per-request of @schandlergarcia after chatting with him. If you check out this repo and switch to the `java-recipes` branch on a Windows machine, all of the line endings are (by default) CRLF. If you then try to start any of the Java functions in a local Docker container, things fail because the Linux host doesn't know how to process those files. I was able to work around this by running `dos2unix` recursively on the `functions` directory.

Hopefully this is something that can be captured in the repo as-is, or perhaps this is just something that must be documented for folks on Windows, but it could be an impediment for Windows folks test-driving Java-based functions via this repo.

### Salesforce Org Type

Scratch Org

### Function Language

Java

### Steps To Reproduce

Should be captured in the summary, but let me know if not.

### Current Behavior

Java functions can't be started in Windows until line endings are changed from CRLF to LF.

### Expected Behavior

Should work without requiring explicit line ending conversions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SCWells72** [comment]
FYI, the same issue occurs on the `prerelease/winter22` branch:

```text
[Executing Maven]
[INFO] $ ./mvnw -DskipTests clean install
/cnb/buildpacks/heroku_maven/0.2.5/bin/build: ./mvnw: /bin/sh^M: bad interpreter: No such file or directory
[ERROR: Failed to build app with Maven]
We're sorry this build is failing! If you can't find the issue in application code,
please submit a ticket so we can help: https://help.heroku.com/
ERROR: failed to build: exit status 1
ExitError: EEXIT: 0
    at Object.exit (C:\Users\Scott\AppData\Local\@salesforce\cli\node_modules\@oclif\errors\lib\index.js:19:11)
    at EventEmitter.<anonymous> (C:\Users\Scott\AppData\Local\@salesforce\cli\node_modules\@salesforce\plugin-functions\lib\commands\run\function\start.js:59:30)
    at EventEmitter.emit (events.js:400:28)
    at EventEmitter.emit (domain.js:475:12)
    at Interface.<anonymous> (C:\Users\Scott\AppData\Local\@salesforce\cli\node_modules\@heroku\functions-core\dist\benny.js:106:39)
    at Interface.emit (events.js:400:28)
    at Interface.emit (domain.js:475:12)
    at Interface._onLine (readline.js:434:10)
    at Interface._normalWrite (readline.js:588:12)
    at Socket.ondata (readline.js:246:10) {
  oclif: { exit: 0 },
  code: 'EEXIT'
}
```

Things work properly after changing line endings in the Java functions from CRLF to LF.

**Comment by julianduque** [comment]
@SCWells72 Thanks for this report, I think this is related on how git is fetching the files on Windows

Can you tell me the output of `git config core.autocrlf` in your setup?

**Comment by SCWells72** [comment]
Sure:

```
$ git config core.autocrlf
true
```

Certainly if that's the issue, it's easily remedied, but it's also probably worth adding that to `README.md` to help other Windows users avoid this issue as they use the repo to play with and learn functions.

**Comment by SCWells72** [comment]
Hi. I just tried checking out your branch and line endings are still CRLF. Seems like perhaps it should be something like:

```
* text eol=lf
```

or perhaps something more specific like:

```
*.java text eol=lf
pom.xml text eol=lf
mvnw text eol=lf
```

**Comment by julianduque** [comment]
A fix landed in `prerelease/winter22`

cc @pozil @SCWells72
